# Generated by Django 5.1 on 2024-08-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverifyrecord_alter_userprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.TextField(default='', max_length=200, verbose_name='introduction'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='signature',
            field=models.CharField(default='', max_length=100, verbose_name='signature'),
        ),
    ]
