# Generated by Django 5.1 on 2024-08-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_nike_name_userprofile_nick_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='nick_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nike_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='nick_name'),
        ),
    ]
