# Generated by Django 5.1 on 2024-08-17 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userprofile_nick_name_userprofile_nike_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='nike_name',
            new_name='nick_name',
        ),
    ]
