# Generated by Django 5.1 on 2024-08-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_nike_name_userprofile_nick_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default='2024-08-23 13:28:15', verbose_name='time'),
        ),
    ]
