# Generated by Django 5.1 on 2024-08-17 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, default='', max_length=200, verbose_name='Category description')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Publish Time')),
                ('mod_date', models.DateTimeField(auto_now_add=True, verbose_name='Last Modified Time')),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Category',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Article Tag')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Publish Time')),
                ('mod_date', models.DateTimeField(auto_now_add=True, verbose_name='Last Modified Time')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Article Title')),
                ('description', models.TextField(max_length=200, verbose_name='Article Description')),
                ('content', models.TextField(verbose_name='Article Content')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Publish Time')),
                ('mod_date', models.DateTimeField(auto_now_add=True, verbose_name='Last Modified Time')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('tags', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.tag', verbose_name='Article Tags')),
            ],
            options={
                'verbose_name': 'Article Label',
                'verbose_name_plural': 'Article Label',
            },
        ),
    ]
