# Generated by Django 5.1 on 2024-08-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_options_article_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SideBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('display_type', models.PositiveIntegerField(choices=[(1, 'Search'), (2, 'Newest Article'), (3, 'Hottest Article'), (4, 'Recently Comment'), (5, 'Article Archiving'), (6, 'HTML')], default=1, verbose_name='Display types')),
                ('content', models.CharField(blank=True, default='', help_text="Can be empty if setting isn't HTML type", max_length=500, verbose_name='Content')),
                ('sort', models.PositiveIntegerField(default=1, help_text='Larger id with former place', verbose_name='Sort')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Hide'), (2, 'Perform')], default=2, verbose_name='Status')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
            ],
            options={
                'verbose_name': 'Side bar',
                'verbose_name_plural': 'Side bar',
                'ordering': ['-sort'],
            },
        ),
    ]
