# Generated by Django 5.1 on 2024-08-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_sidebar'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_hot',
            field=models.BooleanField(default=False, verbose_name='Is Popular'),
        ),
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Views'),
        ),
    ]
