# Generated by Django 5.1 on 2024-09-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_article_tags_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='Is Draft'),
        ),
    ]
