# Generated by Django 5.1 on 2024-09-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_article_is_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='mod_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modified Time'),
        ),
    ]
